spring:
  application:
    name: exam-backup
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/exam_backup
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

server:
  port: 8080
  servlet:
    context-path: /exam-backup

management:
  endpoints:
    web:
      exposure:
        include:


jwt:
  secret: ${SECRET}
  access:
    token:
      validity: 3
  refresh:
    token:
      validity: 10