#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG


spring:
  application:
    name: exam-backup

  datasource:
    url: jdbc:postgresql://localhost:5432/exam_backup
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    #    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080
  servlet:
    # doesn't work here now, set through bean config
    #    multipart:
    #      enabled: true
    #      max-file-size: -1
    #      max-request-size: -1
    context-path: /exam-backup

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

management:
  endpoints:
    web:
      exposure:
        include: "*"

jwt:
  secret: ${SECRET}
  access:
    token:
      validity: 3
  refresh:
    token:
      validity: 360